* ScrollManager --- JavaScript/Coffescript html DOM layout handler for interactive scroll based sites or campaigns.

** Usage

I need to write something here but untill then checkout [[https://github.com/alexaivars/ScrollManager/blob/master/public_html/index.html][index.html]] 

** Bugs?

There is a test suite but since these are some of my first tests written in and for
coffeescript and jasmin they need more work. 

** Links

- Project at GitHub: [[http://github.com/alexaivars/ScrollManager][http://github.com/alexaivars/ScrollManager]]

** License

ScrollManager is released under the BSD license:

#+BEGIN_EXAMPLE

TERMS OF USE - SCROLL MANAGER

Open source under the BSD License. 

Copyright © 2012 Alexander Aivars
All rights reserved.
 
Redistribution and use in source and binary forms, with or without modification, 
are permitted provided that the following conditions are met:

  * Redistributions of source code must retain the above copyright notice, this list of 
  conditions and the following disclaimer.

  * Redistributions in binary form must reproduce the above copyright notice, this list 
  of conditions and the following disclaimer in the documentation and/or other materials 
  provided with the distribution.

  * Neither the name of the author nor the names of contributors may be used to endorse 
  or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY 
EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED 
AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED 
OF THE POSSIBILITY OF SUCH DAMAGE. 
